### ISSUE TITLE
Giphy rating customization

### ISSUE THREAD

**Issue by shaymdev** [julien-nc/integration_giphy#1]
The new giphy integration is great but I think the ratings need to be customizable.

I know the giphy api supports passing the rating param and can see that this integration hardcodes a `g` rating when fetching trending gifs. I'm thinking either hardcoding the `g` rating for all searches is a safer bet for professional/government/etc use, but providing a configurable option would likely be the best route.

Does this sound like a feasible request?

**Comment by julien-nc** [comment]
Thanks for the suggestion. It makes total sense. Rating can now be globally set in the admin settings. This is available in v1.0.3 which is out.

Feel free to reopen this issue if needed.
Cheers

**Comment by shaymdev** [comment]
Awesome! Thanks for implementing it so quickly. It works great!
