### ISSUE TITLE
Toggle to prevent search integration

### ISSUE THREAD

**Issue by Luticus** [julien-nc/integration_giphy#2]
This integration needs a toggle or method to prevent integration with the default Nextcloud search mechanism. Users may not appreciate every search they make on the cloud going to some 3rd party.

**Comment by Luticus** [comment]
Noticed this one actually seems to have a way to stop this.

**Comment by julien-nc** [comment]
Same problem as with the OpenStreetMap and Peertube integrations, the smart picker provider was not able to search anymore if the unified search provider was disabled in the settings.

This is now fixed.

**Comment by Luticus** [comment]
Yea, I actually noticed that problem too and was thinking of reopening this issue about it. Glad you got it fixed. Guess we're just waiting for a release now.
